# Generated by Django 5.2.2 on 2025-06-09 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupons', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cupons.cupom'),
        ),
        migrations.AddField(
            model_name='venda',
            name='desconto_aplicado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
